yaml_file_type: "ILEX"
data:
  dsI: null
  dsQ: null
  dsU: null
  dsV: null

# parameters unique to FRB
par:
  name:   "FRBXXXXXX"
  RA:     "00:00:00.0000"
  DEC:    "00:00:00.0000"
  DM:     0.0
  bw:     336
  MJD:    0.0
  cfreq:  1271.5
  t_lim_base:  [0.0, 3100.0]
  f_lim_base:  [0.0, 336.0]
  t_ref:  0.0
  nchan:  336
  nsamp:  0
  dt:     0.001
  df:     1.0
  RM:     null
  f0:     null
  pa0:    0.0

# parameters for data processing
metapar:
  t_crop:     [0.0, 1.0]
  f_crop:     [0.0, 1.0]
  terr_crop:  null
  tN:         1
  fN:         1
  zapchan:    null
  norm:       "None"

# parameters to control general use of ILEX
hyperpar:
  verbose:        False
  show_plots:     False
  save_plots:     True
  plot_type:  "lines"
  residuals:      True
  plotPosterior:  True



#---------------------------#
# Additional Script options #

plots:
  plot_type:           "lines"
  plotstyle_file:      null

  # plotting stokes data
  stk2plot:             "IQUV"
  stk_ratio:            False
  Ldebias:              False
  Ldebias_threshold:    2.0
  sigma:                2.0

  # plotting poincare sphere data
  plot_data:        True
  plot_model:       True
  n:                True
  normalise:        True

  # plotting PA
  flipPA:           False


fits:
  # for all fitting methods
  fitmethod:  "bayesian"
  redo:       False

  # for Time scattering fitting
  tscatt:
    npulse:     1
    priors:     {}
    statics:    {}
    fit_params: {}

  # scintillation
  scint:
    priors:     {}
    statics:    {}
    fit_params: {}
    n:          5

  # RM fitting
  fitRM:
    method:     "RMsynth"
    fit_params: {}


multi:
  tcrops: null
  fcrops: null


weights:
  # time weights
  time:
    method: "None"
    W:      null
    x:      null
    norm:   True
    func:   null
    args:   null

  # freq weights
  freq:
    method: "None"
    W:      null
    x:      null
    norm:   True
    func:   null
    args:   null

